doctrine: 
  dbal:
    default_connection: default
    connections: 
      database_driver: pdo_mysql
      database_host: localhost
      database_port: 3306
      database_name: restoran
      database_path: ~
      database_user: root
      database_password: 